spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 246380703851-q0oqjngtma7mnmm1p0f5l3po88uik65j.apps.googleusercontent.com
            clientSecret: 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
